coverage:
  range: 50...75
  status:
    project:
      codeintel:
        paths:
          - cmd/precise-code-intel-*
          - internal/codeintel
          - enterprise/internal/codeintel
      web:
        paths:
          - browser
          - shared
          - web
      backend:
        paths:
          - "*.go"
    patch:
      default:
        target: 5%
comment:
  require_changes: yes
  layout: 'diff, flags, files'
ignore:
  - '**/bindata.go'
